export const ActionTypes = {
    SET_CALLS: "SET_CALLS",
    SET_ARCHIVED_CALLS: "SET_ARCHIVED_CALLS",
    SELECT_CALL: "SELECT_CALL",
    ARCHIVE_CALL: "ARCHIVE_CALL",
    ARCHIVE_ALL: "ARCHIVE_ALL"
}